name: sample workflow
on: push
jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "hello world"
    - name: print present directory
      run: pwd
