name: store and retrive secret
on: push
jobs:
  secrets:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: get secrets
      env:
        username: ${{ secrets.USERNAME }}
      run: echo "storing the secret variable $USERNAME"
    - name: print secret
      run: echo $USERNAME 
