name: store and retrive secret
on: push
jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
    steps:
    - name: get secrets
      run: echo "storing the secret variable $USERNAME"
    - name: print secret
      run: echo $USERNAME
